### ISSUE TITLE
java.lang.NoSuchFieldException

### ISSUE THREAD

**Issue by shikoko** [CuriousNikhil/AsynKio#2]
Hello,

I'm getting a java.lang.NoSuchFieldException whenever I'm trying to make a request. I traced it with the debugger and found out that getDeclaredField() method is throwing that error for the "authority" field as well.

java.lang.NoSuchFieldException: No field host in class Ljava/net/URL; (declaration of 'java.net.URL' appears in /system/framework/core-oj.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at me.nikhilchaudhari.asynkio.request.RequestImpl.toIDN(RequestImpl.kt:174)
        at me.nikhilchaudhari.asynkio.request.RequestImpl.makeRoute(RequestImpl.kt:201)
        at me.nikhilchaudhari.asynkio.request.RequestImpl.<init>(RequestImpl.kt:117)
        at me.nikhilchaudhari.asynkio.core.NetworkCall.request(NetworkCall.kt:115)
        at me.nikhilchaudhari.asynkio.core.NetworkCall.post(NetworkCall.kt:94)
        at me.nikhilchaudhari.asynkio.core.NetworkCall.post$default(NetworkCall.kt:92)
        at com.alfresco.core.data.NetworkProtocolImpl.post(NetworkProtocolImpl.kt:66)
        at com.alfresco.core.data.NetworkProtocol$DefaultImpls.post$default(NetworkProtocol.kt:28)
        at com.alfresco.alfrescocore.MainActivity$onCreate$1.invokeSuspend(MainActivity.kt:31)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:32)
        at kotlinx.coroutines.DispatchedTask$DefaultImpls.run(Dispatched.kt:235)
        at kotlinx.coroutines.DispatchedContinuation.run(Dispatched.kt:81)
        at kotlinx.coroutines.scheduling.Task.run(Tasks.kt:94)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:732)

**Comment by CuriousNikhil** [comment]
I guess the issue is with added support of `Files`. Please use [alpha](https://github.com/CuriousNikhil/AsynKio/releases/tag/v1.0.0-alpha) version : https://github.com/CuriousNikhil/AsynKio/releases/tag/v1.0.0-alpha if you are not playing with Files and Streams over the request. 
Thanks.
